### PR TITLE
Prevent <code> blocks from wrapping lines

### LINKED ISSUE #77: tiny legibility issue in docs (perhaps md limitation)
Re: https://github.com/lektor/lektor-website/blob/master/content/docs/content/contents.lr#L89

On my standard Chrome setup on a Mac, it renders like this:

screen shot 2016-03-02 at 5 15 58 pm

Sure would be nice if those four dashes could be wrapped in `<nobr>`... can either embed the tags right in the md, or style the code tags:

``` css
code { white-space: nowrap; }
```

This may have unintended consequences elsewhere in the docs though, so before I do a PR, I thought I'd just bring it up. :-)

### PR DESCRIPTION
**Pull request by singingwolfboy**
Fixes #77. @mitsuhiko, can you think of any problems this might cause?

### CODE REVIEW

**Comment by mitsuhiko** [comment]
We should probably make sure that this does not apply to `<pre><code>...</code></pre>` which is commonly used.

**Comment by singingwolfboy** [comment]
@mitsuhiko When you have a block of code, aren't the line breaks usually important? I would expect the code block to scroll horizontally rather than wrapping.

**Comment by singingwolfboy** [comment]
Might want to review and merge #114 first, since we'll need to re-run `webpack` in this pull request before merging it.

**Comment by singingwolfboy** [comment]
Now that #114 has been merged, I've rebased this pull request and re-run `webpack` to get the change into the `style.css` file as well.

**Comment by nixjdm** [comment]
Works for me. `white-space: nowrap;` is applied to `code` but not to `<pre><code>`.

**Pull request merged**
