### PR TITLE
Document the XDG_CACHE_HOME environment variable

### PR DESCRIPTION
**Pull request by paternal**

### CODE REVIEW

**Comment by paternal** [comment]
Page https://www.getlektor.com/docs/deployment/travisci/ describes how to cache the lektor directory, but the same method cannot be used with Gitlab pages. This pull request explains an alternative method which works with Gitlab.

**Comment by dairiki** [comment]
You might want to note that setting XDG_CACHE_HOME will also affect the location of caches generated by other programs.  E.g. the settings in your example `.gitlab-ci.yml` will also result in the `pip` wheel cache being cached. (In general, that’s probably a good thing, but it’s good to be aware that that’s happening.)

FWIW, to avoid surprises, my personal preference is to explicitly call out which caches are being cached. e.g.
```yaml
variables:
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/_cache"
cache:
    paths:
      - _cache/pip
      - _cache/lektor
```

**Comment by paternal** [comment]
@dairiki I agree :) 3220662

**Comment by dairiki** [comment]
Merged.  Thank you, @paternal!

**Pull request merged**
