### PR TITLE
Add PyCon PH 2016 to showcase

### PR DESCRIPTION
**Pull request by marksteve**

### CODE REVIEW

**Comment by niijv** [comment]
Hi, would like to merge. Why are there changes to the app.js?

**Comment by marksteve** [comment]
@niijv seems like the jquery dep changed (updated?). Should I remove it from the changeset?

**Comment by niijv** [comment]
Please do. 
You could make another pull request together with the changed files from https://github.com/lektor/lektor-website/tree/master/webpack if you want though.

**Comment by marksteve** [comment]
done :+1:

**Comment by niijv** [comment]
Great!

**Pull request merged**
