### PR TITLE
Added documentation about video FFmpeg support.

### PR DESCRIPTION
**Pull request by runfalk**
Added information about [attachment_type] in Lektor project files.

### CODE REVIEW

**Comment by runfalk** [comment]
Fixes #264

**Comment by xlotlu** [comment]
@runfalk this looks very nice. Shouldn't we merge it?

**Comment by runfalk** [comment]
The only reason I haven't merged it is that I thought things published automatically and this is only on master. It was delivered before the 3.1 release, but was not cherry-picked into it.

**Comment by xlotlu** [comment]
Ok I just did it. ;)

**Pull request merged**
