### PR TITLE
Upgrade all javascript dependencies

### PR DESCRIPTION
**Pull request by do3cc**
This is based on my PR for the webpack subrepo: https://github.com/lektor/lektor-webpack-support/pull/23

With these changes, the site is building locally.
I have updated all versions except bootstrap, bootstrap doesn't even provide an migration guide, I expect it would require major changes.

### CODE REVIEW

**Comment by yagebu** [comment]
Hey, thanks for the PR :)

This does not seem to work for me. I've tried `npm install` and `npx webpack` in the webpack directory, but that just seems to hang (uses 100% CPU and does not seem to do anything). After updating packages with `npm update` it does run but errors out on a ton of errors.

**Comment by yagebu** [comment]
I've managed to get it working, seems there were some dependencies missing (and the webpack config needed fixing). Will push to this branch.

> bootstrap doesn't even provide an migration guide

It does: https://getbootstrap.com/docs/4.6/migration/ and https://getbootstrap.com/docs/5.1/migration/
But that might indeed be a larger change best left for a separate PR.

**Comment by do3cc** [comment]
Hi @yagebu sorry for the effort it created for you. I really aimed for having it merge able.

**Comment by yagebu** [comment]
> Hi @yagebu sorry for the effort it created for you. I really aimed for having it merge able.

No worries, thanks again for the PR - it was probably very mergeable back in November and I guess some node package was to blame for the breakage :)

**Pull request merged**
