### PR TITLE
Add lektor-pythonmarkdown plugin page

### PR DESCRIPTION
**Pull request by ikus060**
I've complete all my work and test on the pythonmarkdown plugin. It's ready for public ! So I want it to be shown on lektor website

### CODE REVIEW

**Comment by ikus060** [comment]
@nixjdm Any reason not to accept this merge request ?

**Comment by nixjdm** [comment]
Excellent! Thanks!

> Any reason not to accept this merge request ?

Not really! I was just swamped with other things for a bit, sorry! :grimacing: 

I do have two thoughts though:

1.  I did not specify anywhere that comments should be on, so that's on me and I'll now mention that somewhere. I'd like to remove that bit.
1. We need to add some tags. At minimum: markdown, setup-env

I'll leave this up for a bit if you want to make those changes. If you can't get to it I can though.

**Comment by ikus060** [comment]
@nixjdm I've made the changes.

**Comment by nixjdm** [comment]
Thank you! And thanks for catching the rst page's duplicate tag!

**Pull request merged**
