### PR TITLE
add eswarm.in to showcase

### PR DESCRIPTION
**Pull request by eswarm**
add eswarm.in to showcase

### CODE REVIEW

**Comment by nixjdm** [comment]
@eswarm Sorry this has hung out here forever!

**Comment by dairiki** [comment]
@eswarm The link to your website (http://eswarm.in) seems to no longer work.  Is there a new one?

**Comment by eswarm** [comment]
Hi @dairiki, The url is fixed, I have moved away from Lektor now though, should I submit a PR to remove from the showcase ?

**Comment by dairiki** [comment]
Hi @eswarm —  Sorry to see you go, but I can remove the listing from the showcase — no PR necessary.

**Pull request merged**
