### PR TITLE
Add www.amin.space to the showcase section

### PR DESCRIPTION
**Pull request by mesbahamin**
I'm doing this as a result of mesbahamin/amin.space#1
- [x] Images have a `1.6:1` aspect ratio
- [x] Spell checked
- [x] I used `lektor server` while making changes, so I'm relatively confident this shouldn't break anything

### CODE REVIEW

**Comment by nixjdm** [comment]
It looks like we need to make a change to our css :/ Otherwise it looks good to me. After that's fixed we'll pull this in.

showcase

**Comment by nixjdm** [comment]
@mesbahamin thanks for the patience! I've fixed the layout and I'll pull this now!

**Comment by dairiki** [comment]
@mesbahamin The link to your site sourcecode listed in the showcase (https://github.com/mesbahamin/amin.space) seems no longer to be valid.  Is there a new URL for that?

**Comment by mesbahamin** [comment]
Ah. Sorry for the dead link! I no longer use lektor for my site, so it's probably best to remove it from the gallery altogether.

**Comment by dairiki** [comment]
@mesbahamin No problem.  I will remove the showcase page.

That same broken URL appears in the [README for lektor-webdav](https://github.com/mesbahamin/lektor-webdav/blob/master/README.md) (where it says "My full site configuration can be found here").
(That makes its way through PyPI to https://www.getlektor.com/plugins/lektor-webdav/.)

You may want to remove that link.

**Comment by mesbahamin** [comment]
Feel free to remove lektor-webdav from the lektor site too. I don't use/maintain it anymore, and don't really use Python/PYPI. So even if I update the repo I doubt I will take the time to update the PYPI package.

**Pull request merged**
