### PR TITLE
added page for bibtex-support plugin

### PR DESCRIPTION
**Pull request by arunpersaud**

### CODE REVIEW

**Comment by nixjdm** [comment]
Thank you for your submission!

Could you please add at some tags for this page? At least `setup-env` and `jinja globals`, and maybe `LaTeX`?

**Comment by arunpersaud** [comment]
Added some tags, not 100% how the tag mechanism works, hope I got this right.

**Comment by nixjdm** [comment]
This PR looks good!

A note about the readme though, https://pypi.org/project/lektor-bibtex-support/0.1/ isn't rendering as markdown. This might be because your wheel, twine, or setuptools aren't up-to-date, since 'text/markdown' is pretty new. You may want to check that. In general, getlektor will render the markdown iff pypi does.

**Comment by arunpersaud** [comment]
will try this out. This was the first time I submitted something to PyPi and I ran into several issues. First of all, publishing with lektor directly didn't work (there seems already to be an issue open for it) and then my twine was outdated... I also had to install wheel. I normally use the packages that come with my distribution (openSUSE) and I think they have several updates pending for those packages. I will try again in a few days.

**Comment by nixjdm** [comment]
> I normally use the packages that come with my distribution (openSUSE)

Oh yeah, I would expect OS level packages for python to be somewhat out of date, and the `text/markdown` stuff is only a couple months old. I highly recommend (for python work) to use some sort of virtual environment to straighten out package management.

> publishing with lektor directly didn't work

Can you elaborate? Does https://github.com/lektor/lektor/issues/536 fit your problem?

**Comment by nixjdm** [comment]
@arunpersaud I'm going to go ahead an pull this. The PR is good and a long_description will still appear and be readable.

I do encourage you to reupload a version bump with updated packages, to have the markdown be rendered. I've add notes about that here: https://www.getlektor.com/docs/plugins/publishing/#listing-on-this-site. When you do, this site will take the update on its next build which is at least daily.

Thanks! And invite to the plugin-devs group incoming.

**Comment by arunpersaud** [comment]
if I update all the required packages (wheel, etc) how do I know if the markup upload works? Do I need to upload a new version for every test I do or can I just reupload the package (nothing will have changed after all)?

**Comment by nixjdm** [comment]
@arunpersaud You can upload to https://test.pypi.org/. I don't have recent experience with that since the old site was replaced. It used to be (I think) that version names still needed to be unique. So if you test it there, you may want to go with a version name you don't care about, like 0.1b or something.

**Pull request merged**
